"""add transaction_hash

Revision ID: e254012c9ce2
Revises: 5cd5013724e0
Create Date: 2026-02-17 20:38:52.174734

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import hashlib
from decimal import Decimal


# revision identifiers, used by Alembic.
revision: str = 'e254012c9ce2'
down_revision: Union[str, None] = '5cd5013724e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1) Add as NULLable first (otherwise existing rows violate NOT NULL)
    op.add_column(
        "transactions",
        sa.Column("transaction_hash", sa.String(length=64), nullable=True),
    )

    # created_at is safe as NOT NULL because it has a server_default
    op.add_column(
        "transactions",
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
    )

    # 2) Backfill existing rows
    bind = op.get_bind()

    rows = bind.execute(sa.text("""
        SELECT id, date, description, amount, account, currency
        FROM transactions
        WHERE transaction_hash IS NULL
    """)).mappings().all()

    for r in rows:
        # normalize amount consistently (2 decimals like your Numeric(12,2))
        amt = Decimal(str(r["amount"])).quantize(Decimal("0.01"))
        key = (
            f'{r["date"].isoformat()}|{r["description"]}|{format(amt, "f")}|'
            f'{r["account"] or ""}|{r["currency"] or ""}'
        )
        h = hashlib.sha256(key.encode("utf-8")).hexdigest()

        bind.execute(
            sa.text("UPDATE transactions SET transaction_hash = :h WHERE id = :id"),
            {"h": h, "id": r["id"]},
        )

    # (Optional but common) If you already ingested duplicates previously,
    # the unique index step will fail. This removes exact duplicates by hash, keeping lowest id.
    # If you don't want any automatic deletion, comment this out and clean duplicates manually.
    bind.execute(sa.text("""
        DELETE FROM transactions t
        USING transactions t2
        WHERE t.transaction_hash = t2.transaction_hash
          AND t.id > t2.id;
    """))

    # 3) Enforce constraints after data is valid
    op.alter_column("transactions", "transaction_hash", nullable=False)

    op.create_index(
        op.f("ix_transactions_transaction_hash"),
        "transactions",
        ["transaction_hash"],
        unique=True,
    )





def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_transaction_hash'), table_name='transactions')
    op.drop_column('transactions', 'created_at')
    op.drop_column('transactions', 'transaction_hash')
    # ### end Alembic commands ###
